openapi: 3.0.0
info:
  title: Beneficiary Details API
  version: 1.0.1
  description: API for Source BB to retrieve beneficiary details.

paths:
  /beneficiary/:
    get:
      summary: Retrieve beneficiary details based on payeeIdentity.
      parameters:
        - name: payeeIdentity
          in: query
          required: true
          description: The functional Id of the beneficiaries.
          schema:
            type: string
            maxLength: 20
        - name: requestId
          in: query
          required: true
          description: Request ID.
          schema:
            type: string
            maxLength: 12
        - name: X-Callback_URL
          in: header
          required: true
          description: Callback URL.
          schema:
            type: string
            maxLength: 20
        - name: registeringInstitutionId
          in: header
          required: true
          description: Id of registering Institution.
          schema:
            type: string
            maxLength: 20
      responses:
        '200':
          description: Successfully retrieved beneficiary details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  paymentModalityList:
                    type: array
                    items:
                      type: object
                      properties:
                        payeeIdentity:
                          type: string
                        paymentModality:
                          type: string
                        financialAddress:
                          type: string
                        bankingInstitutionCode:
                          type: string

