openapi: 3.0.0
info:
  title: Financial Address Validation API
  version: 1.0.2
  description: API for the validation of destination accounts/wallets before disbursement.
paths:
  /beneficiaries?command=validate:
    post:
      summary: Financial Address Validation.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - batchId
                - destinationDFSPID
                - creditInstructions
              properties:
                batchId:
                  type: string
                  maxLength: 50
                destinationDFSPID:
                  type: string
                  maxLength: 11
                creditInstructions:
                  type: array
                  items:
                    type: object
                    required:
                      - instructionID
                      - financialAddress
                    properties:
                      instructionID:
                        type: string
                        maxLength: 16
                      financialAddress:
                        type: string
                        maxLength: 20
                      amount:
                        type: number
                        format: float
                      currency:
                        type: string
                        maxLength: 3
                      narration:
                        type: string
                        maxLength: 50
      responses:
        '202':
          description: Accepted. Address validation is underway.
        '400':
          description: Bad Request. Invalid input or malformed request.

      parameters:
        - name: X-Client-Correlation-ID
          in: header
          required: true
          description: Unique Request Id
          schema:
            type: string
            maxLength: 20
        - name: X-Registering-Institution-ID
          in: header
          required: true
          description: ID used for data scoping like Tenants
          schema:
            type: string
            maxLength: 20
        - name: X-Callback-URL
          in: header
          required: true
          description: URL on which the result is published
          schema:
            type: string
            maxLength: 100
