openapi: 3.0.0
info:
  title: Batch Funds Authorization API
  version: 1.0.1
  description: API to get confirmation that sufficient funds have been provisioned within the Payer Bank for a batch to be executed.
paths:
  /batches/{batchId}:
    post:
      summary: Authorize Funds for a Batch Execution.
      parameters:
        - name: batchId
          in: path
          required: true
          description: Batch ID for which this authorization is being sought.
          schema:
            type: string
            maxLength: 50
        - name: command
          in: query
          required: true
          description: Command for action.
          schema:
            type: string
            enum: [authorize]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - batchID
                - payerIdentifier
                - currency
                - amount
              properties:
                batchID:
                  type: string
                  maxLength: 50
                payerIdentifier:
                  type: string
                  maxLength: 20
                  description: IBAN/Account Number of the Disbursing Agency or Registering Institution held within the Payer FI.
                currency:
                  type: string
                  maxLength: 3
                amount:
                  type: number
                  format: float
                  description: Aggregate amount of the batch that would be debited upto 2 decimal points.
      responses:
        '202':
          description: Accepted. Funds authorization is being processed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Authorization is in process."
        '400':
          description: Bad Request. Invalid input or missing parameters.
      parameters:
        - name: X-Client-Correlation-ID
          in: header
          required: true
          description: Globally unique ID.
          schema:
            type: string
            maxLength: 20
