openapi: 3.0.0
info:
  title: RTP Response API to Payments BB
  version: 1.0.0
  description: API called by Payer FI to send RTP Response to Payments BB.
paths:
  /rtpResponse:
    post:
      summary: Send RTP Response to Payments BB.
      parameters:
        - name: X-CorrelationID
          in: header
          required: true
          description: Globally unique requestId/ client correlation Id
          schema:
            type: string
            maxLength: 20
        - name: X-Platform-TenantId
          in: header
          required: true
          description: Tenant Id for Data scoping
          schema:
            type: string
            maxLength: 20
        - name: X-billerId
          in: header
          required: true
          description: ID of the institution initiating the RTP
          schema:
            type: string
            maxLength: 20
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestId:
                  type: string
                  maxLength: 12
                txnId:
                  type: string
                  maxLength: 12
                rtpId:
                  type: integer
                billId:
                  type: string
                  maxLength: 30
                rtpStatus:
                  type: string
                  maxLength: 2
                  enum:
                    - "00"
                    - "01"
                rejectReason:
                  type: string
                  maxLength: 10
                  nullable: true
      responses:
        '200':
          description: RTP Response Acknowledged
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    maxLength: 2
                  responseDescription:
                    type: string
                    maxLength: 200
                  requestID:
                    type: string
                    maxLength: 12
      security:
        - PaymentsBBAuth: []
components:
  securitySchemes:
    PaymentsBBAuth:
      type: apiKey
      in: header
      name: X-CorrelationID
