openapi: 3.0.0
info:
  title: Batch Details API
  version: 1.0.1
  description: API for polling the Batch Details in a paginated way.

paths:
  /api/v1/batch/detail:
    get:
      summary: Retrieve batch details in a paginated way.
      parameters:
        - name: batchId
          in: query
          required: true
          description: Unique ID of the batch transaction.
          schema:
            type: string
            maxLength: 50
        - name: direction
          in: query
          required: false
          description: The direction of the transaction. (e.g. OUTGOING)
          schema:
            type: string
            maxLength: 12
        - name: pageNo
          in: query
          required: false
          description: Offset of the result pages.
          schema:
            type: integer
        - name: pageSize
          in: query
          required: false
          description: Number of results per page.
          schema:
            type: integer
        - name: X-CorrelationID
          in: query
          required: false
          description: Client correlation id of the batch transaction for querying.
          schema:
            type: string
            maxLength: 20
        - name: status
          in: query
          required: false
          description: Status for querying.
          schema:
            type: string
        - name: Platform-TenantId
          in: header
          required: true
          description: ID for data scoping.
          schema:
            type: string
            maxLength: 20
      responses:
        '200':
          description: Successfully retrieved batch details.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    workflowInstanceKey:
                      type: string
                    transactionId:
                      type: string
                    startedAt:
                      type: string
                      format: date-time
                    completedAt:
                      type: string
                      format: date-time
                    status:
                      type: string
                    statusDetail:
                      type: string
                    payeeDfspId:
                      type: string
                    payeePartyId:
                      type: string
                    payeePartyIdType:
                      type: string
                    payeeFee:
                      type: number
                      format: float
                    payeeFeeCurrency:
                      type: string
                    payerDfspId:
                      type: string
                    payerPartyId:
                      type: string
                    payerPartyIdType:
                      type: string
                    payerFee:
                      type: number
                      format: float
                    payerFeeCurrency:
                      type: string
                    amount:
                      type: number
                      format: float
                    currency:
                      type: string
                    direction:
                      type: string
                    errorInformation:
                      type: string
                    batchId:
                      type: string

