openapi: 3.0.0
info:
  title: Payer Bank Validation Response API
  version: 1.0.1
  description: API for Payer Bank to respond to the Bulk_ValidateAccount() request.
paths:
  /callback:
    post:
      summary: Payer Bank Response to Bulk_ValidateAccount.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - clientCorrelationId
                - batchId
                - numberOfFailedCases
              properties:
                clientCorrelationId:
                  type: string
                  maxLength: 12
                batchId:
                  type: string
                  maxLength: 50
                numberOfFailedCases:
                  type: integer
                  format: int32
                failedAccountLookups:
                  type: array
                  items:
                    type: object
                    required:
                      - instructionID
                    properties:
                      instructionID:
                        type: string
                        maxLength: 16
                      failureReason:
                        type: string
                        maxLength: 100
      responses:
        '200':
          description: Success. Payer Bank has successfully responded.
        '202':
          description: Accepted. Response from Payer Bank has been acknowledged.

      parameters:
        - name: X-Callback-URL
          in: header
          required: true
          description: URL from which the original request was received
          schema:
            type: string
