ph-ee-g2psandbox:
  ph-ee-engine:
   
    zeebe-cluster-helm:
      enabled: true

      elasticsearch:
        enabled: false
      kibana:
        enabled: true

    zeebe-operate-helm:
      ingress:
        enabled: false
      
    kibana:
      ingress:
      enabled: false 

    operations:
      
    ph_ee_connector_ams_mifos:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-ams-mifos:v1.4.0
      ingress:
        enabled: false                 

    ph_ee_connector_mojaloop:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-mojaloop:v1.3.0
      ingress:
        enabled: false

    # kafka:

    channel:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-channel:v1.7.0
      operations:
        url: "http://ops-bk.sandbox.fynarfin.io/api/v1"
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"   
      ingress:
        enabled: false
             
    operations_app:
      enabled: true
      image: docker.io/openmf/ph-ee-operations-app:v1.6.0
      tenants: "rhino,gorilla"
      ingress:
        enabled: false

    operations_web:
      enabled: true 
      image: docker.io/openmf/ph-ee-operations-web:v1.4.0
      ingress:
        enabled: false           

    ph_ee_connector_gsma:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-gsma:v1.1.0
      ingress:
        enabled: false

    ph_ee_connector_slcb:
      enabled: false
    
    mpesa:
      enabled: false
      
    roster_connector:
      enabled: false
      
    paygops_connector:
      enabled: false
      
    notifications:
      enabled: true
      image: docker.io/openmf/ph-ee-notifications:v1.3.0
      NOTIFICATION_FAILURE_ENABLED: "false"
      ingress:
        enabled: false 

    connector_bulk:
      enabled: true
      image: docker.io/openmf/ph-ee-bulk-processor:v1.7.0
      tenants: "rhino,gorilla"
      aws:
        region: "us-east-2"
        access_key: "AKIAX32JM37TZOJ5AKFB"
        secret_key: "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"
      operations_app:
        contactpoint: "https://ops-bk.sandbox.fynarfin.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"  
      ingress:
        enabled: false

    zeebe_ops:
      enabled: true
      image: docker.io/openmf/ph-ee-zeebe-ops:v1.2.0
      tenants: "rhino,gorilla"
      ingress:
        enabled: false

    messagegateway:
      enabled: true
      image: docker.io/openmf/message-gateway:v1.0.0
      secret:
        value:
          api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
          project_id: "PJ5ff552ce01d2978c"
      ingress:
        enabled: false
                            
    importer_es:
      enabled: true
      image: docker.io/openmf/ph-ee-importer-es:v1.6.0

    importer_rdbms:
      enabled: true
      image: docker.io/openmf/ph-ee-importer-rdbms:v1.5.0

    wildcardhostname: ""
    tls: ""

    keycloak:
      enabled: false
      ingress:
        enabled: false

    kong:
      enabled: false
      ingress:
        enabled: false

    redis:
      enabled: true
      replica:
        replicaCount: 0
        