openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Beneficiary Onboarding API"
  description: "This is the API that is called by the Information Mediator BB when the Registration BB in turn calls its API for registering beneficiaries into the ID Mapper of the Payments BB."
paths:
  /registerBeneficiaries:
    post:
      summary: "Register beneficiaries"
      description: "Register beneficiaries into the ID Mapper of the Payments BB"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterBeneficiaryRequest"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterBeneficiaryResponse"
              examples:
                success:
                  value:
                    responseCode: "00"
                    responseDescription: "Request successfully received by Pay-BB"
                    requestId: "915251236706"
                failure:
                  value:
                    responseCode: "01"
                    responseDescription: "Request not acknowledged by Pay-BB"
                    requestId: "915251236706"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Register"
  /updateBeneficiaryDetails:
    post:
      summary: Update beneficiary details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestID:
                  type: string
                  minLength: 12
                  maxLength: 12
                SourceBBID:
                  type: string
                  minLength: 12
                  maxLength: 12
                Beneficiaries:
                  type: array
                  items:
                    type: object
                    properties:
                      PayeeFunctionalID:
                        type: string
                        minLength: 20
                        maxLength: 20
                      PaymentModality:
                        type: string
                        minLength: 2
                        maxLength: 2
                      FinancialAddress:
                        type: string
                        maxLength: 30
  /updateBeneficiaryDetails:
      description: Update Beneficiary Details
      request:
        method: POST
        parameters:
          - name: requestId
            type: string
            minLength: 12
            maxLength: 12
            required: true
            description: Globally unique ID
          - name: sourceBBId
            type: string
            minLength: 12
            maxLength: 12
            required: true
            description: To identify the origination of the request
          - name: beneficiaries
            type: array
            items:
              type: object
              properties:
                - name: payeeFunctionalID
                  type: string
                  minLength: 20
                  maxLength: 20
                  required: true
                  description: The functional Id of the beneficiary
                - name: paymentModality
                  type: string
                  minLength: 2
                  maxLength: 2
                  required: false
                  description: >
                    00 for Bank Account
                    01 for Mobile Money
                    02 for Voucher
                    03 for Digital Wallet
                    04 for Proxy
                - name: financialAddress
                  type: string
                  minLength: 30
                  maxLength: 30
                  required: false
                  description: >
                    Destination Account Number, ideally an IBAN if available otherwise wallet destination accounts could be phone numbers as well, other Financial Addresses such as Aliases etc.
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    minLength: 2
                    maxLength: 2
                  ResponseDescription:
                    type: string
                    maxLength: 200
                  RequestID:
                    type: string
                    minLength: 12
                    maxLength: 12
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    minLength: 2
                    maxLength: 2
                  ResponseDescription:
                    type: string
                    maxLength: 200
                  RequestID:
                    type: string
                    minLength: 12
                    maxLength: 12
      examples:
        - request:
            body:
              requestId: "915251236706"
              sourceBBId: "467028349179"
              beneficiaries:
                - payeeFunctionalID: "94049169714828912115"
                  paymentModality: "00"
                  financialAddress: "LB28369763644714781256435714"
                - payeeFunctionalID: "76032553265657618183"
                  paymentModality: "01"
                  financialAddress: "PK36RWHD3218721458424734"
                - payeeFunctionalID: "51498584148040549469"
                - payeeFunctionalID: "69028769626982342710"
                  paymentModality: "02"
          response:
            success:
              code: "00"
              description: "Request successfully received by Pay-BB"
              requestId: "915251236706"
            failure:
              code: "01"
              description: "Request not acknowledged by Pay-BB"
              requestId: "915251236706"
components:
  schemas:
    UpdateBeneficiaryDetailsResponse:
      description: Update Beneficiary Details Response
      request:
        method: POST
        parameters:
          - name: requestId
            type: string
            minLength: 12
            maxLength: 12
            required: true
            description: Globally unique ID
          - name: registerRequestId
            type: string
            minLength: 12
            maxLength: 12
            required: true
            description: Referenced GUID of original request by Source BB to register a beneficiary
          - name: numberFailedCases
            type: number
            required: true
            description: The number of cases failed. 0 if none, otherwise integer value
          - name: failedCases
            type: array
            items:
              type: object
              properties:
                - name: payeeFunctionalId
                  type: string
                  minLength: 20
                  maxLength: 20
                  required: true
                  description: The functional Id of the beneficiary
                - name: paymentModality
                  type: string
                  minLength: 2
                  maxLength: 2
                  required: true
                  description: >
                    00 for Bank Account
                    01 for Mobile Money
                    02 for Voucher
                    03 for Digital Wallet
                    04 for Proxy
                - name: failureReason
                  type: string
                  minLength: 1
                  maxLength: 100
                  required: false
                  description: Description of why this particular record failed to add
      response:
        parameters:
          - name: responseCode
            type: string
            minLength: 2
            maxLength: 2
            required: true
            description: 00 - Success, 01 - Failure
          - name: responseDescription
            type: string
            minLength: 1
            maxLength: 200
            required: true
            description: Response description
          - name: requestId
            type: string
            minLength: 12
            maxLength: 12
            required: true
            description: Echoed from Request
      examples:
        - request:
            body:
              successCase:
                requestId: "291535126670"
                registerRequestId: "915251236706"
                numberFailedCases: 0
              failureCase:
                requestId: "291535126670"
                registerRequestId: "915251236706"
                numberFailedCases: 2
                failedCases:
                  - payeeFunctionalId: "94049169714828912115"
                    paymentModality: "00"
                    failureReason: "Beneficiary already registered"
                  - payeeFunctionalId: "69028769626982342710"
                    paymentModality: "02"
                    failureReason: "Beneficiary already registered"
          response:
            success:
              code: "00"
              description: "Request successfully received by IM BB"
              requestId: "291535126670"

