openapi: 3.0.0
info:
  title: PrePayment Validation API
  version: 1.0.0
paths:
  /prepaymentValidation:
    post:
      operationId: PrePaymentValidation
      description: This API is to be exposed by the Payments BB; it will be called by the Source BB to gather details on which of the Functional IDs they would have previously stored in the account mapper are in a position to receive a credit transfer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requestID:
                  type: string
                  description: Globally unique ID
                sourceBBID:
                  type: string
                  description: To identify the origination of the request.
                batchID:
                  type: string
                  description: BatchID for batch that is submitted by the Source BB.
                creditInstructions:
                  type: array
                  description: List of credit instructions
                  items:
                    type: object
                    properties:
                      instructionID:
                        type: string
                        description: Individual ID for each instruction in the Credit Batch
                      payeeFunctionalID:
                        type: string
                        description: The functional Id of the beneficiary.
                      amount:
                        type: number
                        description: Amount to be Credited
                      currency:
                        type: string
                        description: Transaction Currency Code
                      narration:
                        type: string
                        description: Description of Payment
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    description: 00 – Success 01 – Failure
                  responseDescription:
                    type: string
                    description: ResponseDescription
                  requestID:
                    type: string
                    description: Echoed from Request
  /prepaymentValidationResponse:
    post:
      operationId: PrePaymentValidationResponse
      description: Response to the earlier request for validation of receiving accounts prior to initiation of the Bulk Payments Batch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requestID:
                  type: string
                  description: Globally unique ID
                source_BatchID:
                  type: string
                  description: Echo referenced GUID of original request by Source BB to validate a batch of instructions.
                numberFailedCases:
                  type: number
                  description: The number of cases failed. 0 if none, otherwise integer value
                failedAccounts:
                  type: array
                  description: List of accounts that failed to validate credit status.
                  items:
                    type: object
                    properties:
                      instructionID:
                        type: string
                        description: Individual ID for each instruction in the Credit Batch
                      failureReason:
                        type: string
                        description: Description of why this particular account failed to validate
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    description: 00 – Success 01 – Failure
                  responseDescription:
                    type: string
                    description: ResponseDescription
                  requestID:
                    type: string
                    description: Echoed from Request
