openapi: 3.0.0
info:
  title: PrePayment Validation API
  version: 1.0.0
servers:
  - url: 
paths:
  /prepayment-validation:
    post:
      operationId: PrePayment_Validation
      description: This API is to be exposed by the Payments BB; it will be called by the Source BB to gather details on which of the Functional IDs they would have previously stored in the account mapper are in a position to receive a credit transfer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestID:
                  type: string
                  description: Globally unique ID
                SourceBBID:
                  type: string
                  description: To identify the origination of the request.
                BatchID:
                  type: string
                  description: BatchID for batch that is submitted by the Source BB.
                CreditInstructions:
                  type: array
                  description: List of credit instructions
                  items:
                    type: object
                    properties:
                      InstructionID:
                        type: string
                        description: Individual ID for each instruction in the Credit Batch
                      PayeeFunctionalID:
                        type: string
                        description: The functional Id of the beneficiary.
                      Amount:
                        type: number
                        description: Amount to be Credited
                      Currency:
                        type: string
                        description: Transaction Currency Code
                      Narration:
                        type: string
                        description: Description of Payment
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    description: 00 – Success 01 – Failure
                  ResponseDescription:
                    type: string
                    description: ResponseDescription
                  RequestID:
                    type: string
                    description: Echoed from Request
  /prepayment-validation-response:
    post:
      operationId: PrePayment_Validation_Response
      description: Response to the earlier request for validation of receiving accounts prior to initiation of the Bulk Payments Batch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestID:
                  type: string
                  description: Globally unique ID
                Source_BatchID:
                  type: string
                  description: Echo referenced GUID of original request by Source BB to validate a batch of instructions.
                NumberFailedCases:
                  type: number
                  description: The number of cases failed. 0 if none, otherwise integer value
                FailedAccounts:
                  type: array
                  description: List of accounts that failed to validate credit status.
                  items:
                    type: object
                    properties:
                      InstructionID:
                        type: string
                        description: Individual ID for each instruction in the Credit Batch
                      FailureReason:
                        type: string
                        description: Description of why this particular account failed to validate
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    description: 00 – Success 01 – Failure
                  ResponseDescription:
                    type: string
                    description: ResponseDescription
                  RequestID:
                    type: string
                    description: Echoed from Request
